# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dhandelion
tagline:          Cyber Blog and Other Computery Stuff
description:      Blog Bogey
url:              "https://thedhandelion.github.io"
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0
